### ISSUE TITLE
Broken on python >=3.10

### ISSUE THREAD

**Issue by chillenb** [conda-forge/pyfive-feedstock#4]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

This package doesn't work with python >= 3.10, since it does `from collections import Mapping`.

### Installed packages

# packages in environment at /home/chillenb/mambaforge/envs/pyfiveenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_0    conda-forge
libsqlite                 3.47.0               hadc24fc_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
numpy                     2.1.2           py310hd6e36ab_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pyfive                    0.3.0                      py_0    conda-forge
python                    3.10.15         h4a871b0_2_cpython    conda-forge
python_abi                3.10                    5_cp310    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge

### Environment info

     active environment : pyfiveenv
    active env location : /home/chillenb/mambaforge/envs/pyfiveenv
            shell level : 1
       user config file : /home/chillenb/.condarc
 populated config files : /home/chillenb/mambaforge/.condarc
                          /home/chillenb/.condarc
          conda version : 24.9.2
    conda-build version : not installed
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen3
                          __conda=24.9.2=0
                          __cuda=12.6=0
                          __glibc=2.40=0
                          __linux=6.10.10=0
                          __unix=0=0
       base environment : /home/chillenb/mambaforge  (writable)
      conda av data dir : /home/chillenb/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
          package cache : /home/chillenb/mambaforge/pkgs
                          /home/chillenb/.conda/pkgs
       envs directories : /home/chillenb/mambaforge/envs
                          /home/chillenb/.conda/envs
               platform : linux-64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.7 Linux/6.10.10-arch1-1 arch/rolling glibc/2.40 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.10
                UID:GID : 1000:1000
             netrc file : /home/chillenb/.netrc
           offline mode : False

**Comment by ocefpaf** [comment]
I'm not sure if this package is still developed. Maybe we should fix that with a repo data patch and archive it.

Pinging @jjhelmus for some advice.

**Comment by jjhelmus** [comment]
:wave: No one is actively working on pyfive that I know of but this issue was address 4 years ago in jjhelmus/pyfive#44. I'll tag a new release, upload it to PyPI and come back here to create a new package.

As for the existing package the repodata could be patched to add an upper bound on the python version. Once the new release is out I'll leave it up to other to decide if it is worth the effort to patch the old release.

**Comment by chillenb** [comment]
@jjhelmus Great, thanks for doing that! Even if pyfive isn't actively developed, it's quite useful for learning about the hdf5 format, recovering corrupt data, etc.

**Comment by jjhelmus** [comment]
A pyfive 0.4.0 package is available that supports Python >=3.10 now that #5 was merged.
